### ISSUE TITLE
BIOS version - is it safe to update?

### ISSUE THREAD

**Issue by postkevone** [KatLantyss/Razer-Blade-Stealth-13-IceLake-Hackintosh#2]
Is it safe to update to BIOS v1.04?
Also, may I ask what is the version of the BIOS you used for this configuration?

Thank you.

**Comment by KatLantyss** [comment]
My System BIOS version is v1.05,so I think is fine to update to v1.04.

**Comment by postkevone** [comment]
On Razer website the latest BIOS listed for the model RZ09-03102 is v1.04.
Where did you get the 1.05 version?

**Comment by KatLantyss** [comment]
I can't recall how I obtained version 1.05, but the primary purpose of BIOS configuration is to unlock and display hidden options in the BIOS settings interface. I believe the BIOS version is not a critical issue.

**Comment by postkevone** [comment]
Unfortunately I discovered that I cannot modify the BIOS by software. I anyway managed to create a pretty solid config for monterey with stock unmodded BIOS.
